### ISSUE TITLE
Function pointers extraction in external code cause exceptions

### ISSUE THREAD

**Issue by slango0513** [nxrighthere/UnrealCLR#14] opened 2020-07-23 16:30 UTC
Cannot call extension methods in external assemblies (such as from NuGet).

Reproduction:
Install any NuGet package which has extension methods for the "UnrealEngine.Tests" or own project, then involke it, the plugin will crash.

**Comment by nxrighthere** [comment] 2020-07-23 16:36
Can you please provide a minimal .NET project with such a package?

**Comment by slango0513** [comment] 2020-07-23 16:53
> Can you please provide a minimal .NET project with such a package?

Thank you for your reply. I use exactly the same config as in the introduction of README.md, it's easy to reproduce this bug:

1. X:\UnrealCLR\Source\Managed\Tests> dotnet add package Microsoft.Extensions.DependencyInjection

2. Open "Tests\InstancedStaticMeshes.cs" with editor.

3. Add `using Microsoft.Extensions.DependencyInjection;`.

4. At the beginning of the “OnBeginPlay” function add following code:
`var x = new ServiceCollection().BuildServiceProvider();`

5. Publish to UE project "Managed" folder, open UE Editor and run.

`BuildServiceProvider()` is an extension method, the plugin will crash here.

**Comment by nxrighthere** [comment] 2020-07-23 17:51
I've reproduced this and found the root of the problem. It will be fixed with early migration to .NET 5, approximately. I just don't have enough of the right API in .NET Core 3 to solve this now from the Unreal's perspective.

**Comment by nxrighthere** [comment] 2020-07-24 12:38
@slango0513 Please, confirm that this issue is now solved for you with the latest version from the master branch.

**Closed as completed** 2020-07-27 12:19 UTC
Labels: bug, external package

**Comment by slango0513** [comment] 2020-07-27 19:20
> @slango0513 Please, confirm that this issue is now solved for you with the latest version from the master branch.

Yes, this issue is solved.
Found some related issues, I provide code snippets in the same way as above:

**Case 1: UE editor will crash** at 'getTask.Result'
**Reproduction:**
```
using System.Net.Http;
...
OnBeginPlay()
{
    var httpClient = new HttpClient();
    try
    {
    	    var getTask = httpClient.GetAsync("https://dotnet.microsoft.com/");
    	    var result = getTask.Result;
	    Debug.Log(LogLevel.Warning, $"Result: {result}");
    }
    catch (Exception e)
    {
	    Debug.Log(LogLevel.Warning, $"Error: {e}");
    }
...
```

**Case 2: Unload assembly fail** with log
'Unloading of assemblies took more time than expected. Trying to unload assemblies to the next breakpoint...'
'Unloading of assemblies was failed! This might be caused by running threads, strong GC handles, or by other sources that prevent cooperative unloading.'

**Reproduction:**
Add package 'Microsoft.Orleans.Client'
```
using Orleans;
...
OnBeginPlay()
{
var client = new ClientBuilder()
    .UseLocalhostClustering()
    .Build();
...
```

**Comment by nxrighthere** [comment] 2020-07-27 19:25
@slango0513 I'll take a look into that.

The second case indicates that one of the systems from external code was not shutdown gracefully, and logic is still running, so the plugin is unable to unload it.

**Comment by slango0513** [comment] 2020-07-27 19:45
> @slango0513 I'll take a look into that.
> 
> The second case indicates that one of the systems from external code was not shutdown gracefully, and logic is still running, so the plugin is unable to unload it.

Okay, I will try to solve it.
It is painful that many external libs don's seem to have a way to dispose them completely, but we have nothing more to do that UE only provides FPlatformProcess::FreeDllHandle(hostfxr)

**Comment by nxrighthere** [comment] 2020-07-27 19:45
@slango0513 I'm unable to reproduce the first case with the latest version from the master branch. It seems that I got a proper output:
```
LogUnrealManaged: Warning: UnrealCLRFramework::Debug::Log: Result: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-store
  Transfer-Encoding: chunked
  X-Cache: TCP_MISS
  Server: Kestrel
  Set-Cookie: TiPMix=7.92543529901907; path=/; HttpOnly; Domain=dotnetwebsite.azurewebsites.net; Max-Age=3600
  Set-Cookie: x-ms-routing-name=preview; path=/; HttpOnly; Domain=dotnetwebsite.azurewebsites.net; Max-Age=3600
  Request-Context: appId=cid-v1:109cec76-ff6c-4be0-97b5-4f02dbac2451
  X-Powered-By: ASP.NET
  X-Content-Type-Options: nosniff
  X-Azure-Ref: 0tS0fXwAAAABpYtatzaM6S7Xkr8POPZAYQU1TRURHRTA2MTQAZTFkZjA3MGEtYWU0NC00YzBiLWE1NGItYzQ5MzgwNGU0ZDlm
  Date: Mon, 27 Jul 2020 19:40:36 GMT
  Content-Type: text/html; charset=utf-8
}
```
Can you please attach a debugger to the editor and inspect what might cause this? Also, try to reproduce this with a newly created Unreal Engine project.

**Comment by nxrighthere** [comment] 2020-07-27 19:47
I'm using Unreal Engine 4.25.2 by the way.

**Comment by nxrighthere** [comment] 2020-07-27 19:56
> It is painful that many external libs don's seem to have a way to dispose them completely, but we have nothing more to do that UE only provides FPlatformProcess::FreeDllHandle(hostfxr)

I feel you, but this is how the assembly load context works in CoreCLR, so external code should support cooperative unloading for hot reload.

**Comment by slango0513** [comment] 2020-07-27 20:24
> I feel you, but this is how the assembly load context works in CoreCLR, so external code should support cooperative unloading for hot reload.

My mistake, I don’t know much about the way of net core 3 assembly loading yet.
After UE updated from 4.25.1 to 4.25.2, HttpClient works well. If it recurs I will reply on this topic.

**Comment by nxrighthere** [comment] 2020-07-27 20:27
@slango0513  Good to know!

> I don’t know much about the way of net core 3 assembly loading yet.

Yes, if you will not figure this out, the best way to solve this is to open a new issue in an appropriate repository of a package (Orleans in this case?) and propose functionality for graceful shutdown in accordance with [this](https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability) article by Microsoft.
