### ISSUE TITLE
Installation fails due to whitespaces in a path to the installation tool

### ISSUE THREAD

**Issue by perkalkyl** [nxrighthere/UnrealCLR#42] opened 2020-09-25 07:47 UTC
Hi! I am Currently evaluating UnrealCLR and have high hopes for it 👍 

Just wanted to inform that the msbuild process fails with a "Can only contain 1 project" error if there is a space anywhere in the path to either the Unreal project or the UnrealCLR code.

Using Windows 10 (x64) and VS2019 preview 

BR
Per

**Comment by nxrighthere** [comment] 2020-09-25 08:01
This case is explicitly handled in the installation tool, and I can't reproduce it on my end. Tell me please the current path from where you are running the installation tool, and the full path to your Unreal Engine project.

**Comment by perkalkyl** [comment] 2020-09-25 09:00
It really isn't a problem for me. Just wanted to give the info in case someone else who isn't used to the limitations of using paths with spaces in command prompt calls gets stuck on this.
Like if I have my UnrealCLR code in "D:\MyCode\Unreal tests\UnrealCLR\" and my Unreal project in "D:\MyCode\Unreal tests\Unreal Projects" it will trigger this issue. If you can't replicate it, it might be a Windows localization issue. For some reason my Windows installation was done in Swedish...

**Comment by nxrighthere** [comment] 2020-09-25 10:56
Thanks for the information, it should be fixed now.

**Closed as completed** 2020-09-25 10:56 UTC
Labels: bug
